/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.buaa.qjjia.model.log;  
@SuppressWarnings("all")
/** A pair of strings */
@org.apache.avro.specific.AvroGenerated
public class Demo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Demo\",\"namespace\":\"edu.buaa.qjjia.model.log\",\"doc\":\"A pair of strings\",\"fields\":[{\"name\":\"left\",\"type\":\"string\"},{\"name\":\"right\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence left;
  @Deprecated public CharSequence right;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Demo() {}

  /**
   * All-args constructor.
   */
  public Demo(CharSequence left, CharSequence right) {
    this.left = left;
    this.right = right;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return left;
    case 1: return right;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: left = (CharSequence)value$; break;
    case 1: right = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'left' field.
   */
  public CharSequence getLeft() {
    return left;
  }

  /**
   * Sets the value of the 'left' field.
   * @param value the value to set.
   */
  public void setLeft(CharSequence value) {
    this.left = value;
  }

  /**
   * Gets the value of the 'right' field.
   */
  public CharSequence getRight() {
    return right;
  }

  /**
   * Sets the value of the 'right' field.
   * @param value the value to set.
   */
  public void setRight(CharSequence value) {
    this.right = value;
  }

  /** Creates a new Demo RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new Demo RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new Demo RecordBuilder by copying an existing Demo instance */
  public static Builder newBuilder(Demo other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for Demo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Demo>
    implements org.apache.avro.data.RecordBuilder<Demo> {

    private CharSequence left;
    private CharSequence right;

    /** Creates a new Builder */
    private Builder() {
      super(Demo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.left)) {
        this.left = data().deepCopy(fields()[0].schema(), other.left);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.right)) {
        this.right = data().deepCopy(fields()[1].schema(), other.right);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Demo instance */
    private Builder(Demo other) {
            super(Demo.SCHEMA$);
      if (isValidValue(fields()[0], other.left)) {
        this.left = data().deepCopy(fields()[0].schema(), other.left);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.right)) {
        this.right = data().deepCopy(fields()[1].schema(), other.right);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'left' field */
    public CharSequence getLeft() {
      return left;
    }
    
    /** Sets the value of the 'left' field */
    public Builder setLeft(CharSequence value) {
      validate(fields()[0], value);
      this.left = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'left' field has been set */
    public boolean hasLeft() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'left' field */
    public Builder clearLeft() {
      left = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'right' field */
    public CharSequence getRight() {
      return right;
    }
    
    /** Sets the value of the 'right' field */
    public Builder setRight(CharSequence value) {
      validate(fields()[1], value);
      this.right = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'right' field has been set */
    public boolean hasRight() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'right' field */
    public Builder clearRight() {
      right = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    public Demo build() {
      try {
        Demo record = new Demo();
        record.left = fieldSetFlags()[0] ? this.left : (CharSequence) defaultValue(fields()[0]);
        record.right = fieldSetFlags()[1] ? this.right : (CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
